apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f python-todolist-app/docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: user-svc
  name: user-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user-svc
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f python-todolist-app/docker-compose.yml
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/python-todolist-app-default: "true"
        io.kompose.service: user-svc
    spec:
      containers:
        - image: 749882936473.dkr.ecr.us-east-2.amazonaws.com/python-user-svc:${REV}
          name: user-svc
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
