version: "2"
services:
  todolist-backend:
    build: ./app
    links:
      - db
      - user-svc
    ports:
      - "6000:6000"
    environment:
      USER_SVC_HOSTPORT: http://user-svc:5000
  db:
    image: mysql:5.7.28
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  user-svc:
    build: ../python-user-svc/app
    links:
      - db
    ports:
      - "8000:8000"
  todolist-web:
    build: ../web-client
    links:
      - user-svc
      - todolist-backend
    environment:
      USER_SVC_HOSTPORT: http://user-svc:5000
      TODOLIST_APP_SVC_HOSTPORT: http://todolist-app:6000
    ports:
      - "8080:8080"
