apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f python-todolist-app/docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: todolist-web
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: todolist-web
status:
  loadBalancer: {}
