apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f python-todolist-app/docker-compose.yml
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: user-svc
  name: user-svc
spec:
  ports:
    - name: "5000"
      port: 5000
      targetPort: 8000
  selector:
    io.kompose.service: user-svc
status:
  loadBalancer: {}
